# Copyright 2025-present DatusAI, Inc.
# Licensed under the Apache License, Version 2.0.

"""DAG source-code generator for the Datus Airflow adapter.

The generated DAG embeds the SQL + connection config as a JSON literal inside
the Python source.  The only Airflow-native dependency is ``sqlalchemy``, which
ships with every Airflow installation.
"""

import json
import logging
import textwrap
from datetime import datetime, timezone
from typing import Optional

logger = logging.getLogger(__name__)


_SPARK_DAG_TEMPLATE = textwrap.dedent(
    '''\
    # ============================================================
    # Auto-generated by Datus Airflow Adapter — DO NOT EDIT
    # Job  : {job_name}
    # Built: {built_at}
    # ============================================================

    from __future__ import annotations

    import json
    from datetime import datetime, timezone

    from airflow import DAG
    from airflow.operators.python import PythonOperator

    _SPARK_CONFIG: dict = {config_json}


    def _run_spark_script(**context: dict) -> None:  # noqa: ANN001
        """Execute the PySpark script configured by Datus."""
        import os

        os.environ.setdefault("SPARK_LOCAL_IP", "127.0.0.1")
        from pyspark import SparkConf, SparkContext  # noqa: PLC0415

        conf = SparkConf().setMaster(_SPARK_CONFIG["spark_master"]).setAppName("DatusSparkJob")
        sc = SparkContext.getOrCreate(conf=conf)
        local_vars = {{"sc": sc}}
        exec(_SPARK_CONFIG["spark_script"], local_vars)  # noqa: S102
        sc.stop()


    with DAG(
        dag_id={dag_id_repr},
        description={description_repr},
        schedule={schedule_repr},
        start_date=datetime({start_year}, {start_month}, {start_day}, tzinfo=timezone.utc),
        end_date={end_date_repr},
        catchup=False,
        tags=["datus", "spark"],
        is_paused_upon_creation=False,
    ) as dag:
        run_spark = PythonOperator(
            task_id="run_spark_script",
            python_callable=_run_spark_script,
        )
    '''
)


_DAG_TEMPLATE = textwrap.dedent(
    '''\
    # ============================================================
    # Auto-generated by Datus Airflow Adapter — DO NOT EDIT
    # Job  : {job_name}
    # Built: {built_at}
    # ============================================================

    from __future__ import annotations

    import json
    from datetime import datetime, timezone

    from airflow import DAG
    from airflow.operators.python import PythonOperator

    _DATUS_CONFIG: dict = {config_json}


    def _resolve_connection_url(db_connection: dict) -> str | None:
        """Resolve a SQLAlchemy connection URL from db_connection config.

        Supports two modes:
          - conn_id: reference an Airflow-managed Connection (preferred)
          - url: explicit SQLAlchemy URL (legacy / testing)
        """
        conn_id: str | None = db_connection.get("conn_id")
        if conn_id:
            from airflow.hooks.base import BaseHook  # noqa: PLC0415

            conn = BaseHook.get_connection(conn_id)
            # DuckDB: Airflow round-trips the URI through component parsing,
            # which can corrupt "duckdb:///path".  Rebuild from conn fields.
            if conn.conn_type == "duckdb":
                from urllib.parse import urlencode  # noqa: PLC0415

                db_path = conn.schema or conn.host or ""
                if not db_path:
                    raise ValueError(
                        "[Datus] Airflow connection '" + conn_id + "' has conn_type=duckdb "
                        "but no database path in schema or host fields."
                    )
                if db_path == ":memory:":
                    url = "duckdb:///:memory:"
                elif db_path.startswith("/"):
                    url = "duckdb:///" + db_path      # absolute: duckdb:////abs/path
                else:
                    url = "duckdb:///" + db_path       # relative: duckdb:///local.db
                # Preserve query parameters from Airflow extras
                query_params = conn.extra_dejson if hasattr(conn, "extra_dejson") else {{}}
                if query_params:
                    url = url + "?" + urlencode(query_params, doseq=True)
                print("[Datus] Using Airflow connection: " + conn_id + " (duckdb)")
                return url
            url = conn.get_uri()
            # Airflow returns "postgres://" but SQLAlchemy 1.4+ requires "postgresql://"
            if url.startswith("postgres://"):
                url = "postgresql://" + url[len("postgres://"):]
            print("[Datus] Using Airflow connection: " + conn_id)
            return url

        return db_connection.get("url")


    def _execute_datus_sql(**context: dict) -> dict:  # noqa: ANN001
        """Execute the SQL configured by Datus."""
        cfg: dict = _DATUS_CONFIG
        sql: str = cfg["sql"]
        db_connection: dict = cfg.get("db_connection") or {{}}

        print("[Datus] Running SQL: " + sql[:200])

        connection_url: str | None = _resolve_connection_url(db_connection)
        if connection_url:
            from sqlalchemy import create_engine, text  # noqa: PLC0415

            engine = create_engine(connection_url)
            columns: list = []
            rows: list = []
            has_more = False
            affected: int = -1
            with engine.connect() as conn:
                result = conn.execute(text(sql))
                returns_rows = result.returns_rows
                if returns_rows:
                    columns = list(result.keys())
                    rows = result.fetchmany(50)
                    has_more = bool(result.fetchone())
                else:
                    affected = result.rowcount if result.rowcount is not None else -1

            if returns_rows:
                row_count = len(rows)
                print(
                    "[Datus] SQL completed. preview_rows="
                    + str(row_count)
                    + (", has_more=True" if has_more else "")
                )
                if columns:
                    print("[Datus] Columns: " + " | ".join(str(c) for c in columns))
                for i, row in enumerate(rows):
                    print("[Datus] Row " + str(i + 1) + ": " + " | ".join(str(v) for v in row))
                if has_more:
                    print("[Datus] ... (more rows available, preview limited to 50)")
            else:
                row_count = affected if affected >= 0 else 0
                affected_display = str(affected) if affected >= 0 else "unknown"
                print("[Datus] SQL completed (no rowset). affected_rows=" + affected_display)

            return {{"status": "success", "row_count": row_count}}

        # No connection configured — succeed with a warning (useful for dry-run / test DAGs).
        print("[Datus] No connection configured; skipping SQL execution.")
        return {{"status": "skipped"}}


    with DAG(
        dag_id={dag_id_repr},
        description={description_repr},
        schedule={schedule_repr},
        start_date=datetime({start_year}, {start_month}, {start_day}, tzinfo=timezone.utc),
        end_date={end_date_repr},
        catchup=False,
        tags=["datus"],
        is_paused_upon_creation=False,
    ) as dag:
        execute_sql = PythonOperator(
            task_id="execute_sql",
            python_callable=_execute_datus_sql,
        )
    '''
)


def render_spark_dag_source(
    dag_id: str,
    job_name: str,
    spark_script: str,
    spark_master: str = "local[*]",
    schedule: Optional[str] = None,
    start_date: Optional[datetime] = None,
    description: Optional[str] = None,
) -> str:
    """Render a Python DAG source string for a generic PySpark script.

    Args:
        dag_id:       Airflow DAG identifier (must be unique across all DAGs).
        job_name:     Human-readable name (embedded as a comment).
        spark_script: Inline PySpark script; ``sc`` (SparkContext) is injected.
        spark_master: Spark master URL, e.g. ``local[*]`` or ``spark://host:7077``.
        schedule:     Cron expression or ``None`` for manual-only.
        start_date:   DAG start date; defaults to 2024-01-01 UTC when ``None``.
        description:  Optional DAG description.

    Returns:
        A string containing valid Python source code for an Airflow DAG file.
    """
    logger.warning(
        "Rendering Spark DAG '%s' with inline script execution (exec()). Ensure the spark_script source is trusted.",
        dag_id,
    )

    config_payload = {
        "spark_script": spark_script,
        "spark_master": spark_master or "local[*]",
    }
    config_json = json.dumps(config_payload, ensure_ascii=False, indent=4)

    effective_start = start_date or datetime(2024, 1, 1, tzinfo=timezone.utc)

    effective_schedule = schedule if schedule and str(schedule).strip().lower() != "none" else None

    return _SPARK_DAG_TEMPLATE.format(
        job_name=job_name,
        built_at=datetime.now(tz=timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
        config_json=config_json,
        dag_id_repr=repr(dag_id),
        description_repr=repr(description or f"Datus Spark job: {job_name}"),
        schedule_repr=repr(effective_schedule),
        start_year=effective_start.year,
        start_month=effective_start.month,
        start_day=effective_start.day,
        end_date_repr="None",
    )


_SPARKSQL_DAG_TEMPLATE = textwrap.dedent(
    '''\
    # ============================================================
    # Auto-generated by Datus Airflow Adapter — DO NOT EDIT
    # Job  : {job_name}
    # Built: {built_at}
    # ============================================================

    from __future__ import annotations

    import json
    from datetime import datetime, timezone

    from airflow import DAG
    from airflow.operators.python import PythonOperator

    _SPARKSQL_CONFIG: dict = {config_json}


    def _run_sparksql(**context: dict) -> dict:  # noqa: ANN001
        """Execute SparkSQL configured by Datus."""
        from pyspark.sql import SparkSession  # noqa: PLC0415

        spark = (
            SparkSession.builder
            .master(_SPARKSQL_CONFIG["spark_master"])
            .appName("DatusSparkSQL")
            .getOrCreate()
        )
        sql: str = _SPARKSQL_CONFIG["sql"]
        print("[Datus] Running SparkSQL: " + sql[:200])
        result = spark.sql(sql)
        count = result.count()
        print("[Datus] SparkSQL completed. rows=" + str(count))
        spark.stop()
        return {{"status": "success", "row_count": count}}


    with DAG(
        dag_id={dag_id_repr},
        description={description_repr},
        schedule={schedule_repr},
        start_date=datetime({start_year}, {start_month}, {start_day}, tzinfo=timezone.utc),
        end_date={end_date_repr},
        catchup=False,
        tags=["datus", "sparksql"],
        is_paused_upon_creation=False,
    ) as dag:
        run_sparksql = PythonOperator(
            task_id="run_sparksql",
            python_callable=_run_sparksql,
        )
    '''
)


def render_sparksql_dag_source(
    dag_id: str,
    job_name: str,
    sql: str,
    spark_master: str = "local[*]",
    schedule: Optional[str] = None,
    start_date: Optional[datetime] = None,
    end_date: Optional[datetime] = None,
    description: Optional[str] = None,
) -> str:
    """Render a Python DAG source string for a SparkSQL query.

    The generated DAG creates a SparkSession and runs the SQL via
    ``spark.sql()``, which supports the full SparkSQL dialect.

    Args:
        dag_id:       Airflow DAG identifier (must be unique across all DAGs).
        job_name:     Human-readable name (embedded as a comment).
        sql:          SparkSQL statement to execute.
        spark_master: Spark master URL, e.g. ``local[*]`` or ``spark://host:7077``.
        schedule:     Cron expression or ``None`` for manual-only.
        start_date:   DAG start date; defaults to 2024-01-01 UTC when ``None``.
        end_date:     Optional DAG end date.
        description:  Optional DAG description.

    Returns:
        A string containing valid Python source code for an Airflow DAG file.
    """
    config_payload = {
        "sql": sql,
        "spark_master": spark_master or "local[*]",
    }
    config_json = json.dumps(config_payload, ensure_ascii=False, indent=4)

    effective_start = start_date or datetime(2024, 1, 1, tzinfo=timezone.utc)
    end_date_repr = (
        f"datetime({end_date.year}, {end_date.month}, {end_date.day}, tzinfo=timezone.utc)" if end_date else "None"
    )

    effective_schedule = schedule if schedule and str(schedule).strip().lower() != "none" else None

    return _SPARKSQL_DAG_TEMPLATE.format(
        job_name=job_name,
        built_at=datetime.now(tz=timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
        config_json=config_json,
        dag_id_repr=repr(dag_id),
        description_repr=repr(description or f"Datus SparkSQL job: {job_name}"),
        schedule_repr=repr(effective_schedule),
        start_year=effective_start.year,
        start_month=effective_start.month,
        start_day=effective_start.day,
        end_date_repr=end_date_repr,
    )


def render_dag_source(
    dag_id: str,
    job_name: str,
    sql: str,
    db_connection: Optional[dict],
    schedule: Optional[str],
    start_date: Optional[datetime],
    end_date: Optional[datetime],
    description: Optional[str],
) -> str:
    """Render a Python DAG source string from the template.

    Args:
        dag_id:        Airflow DAG identifier (must be unique across all DAGs).
        job_name:      Human-readable name (embedded as a comment).
        sql:           SQL statement to execute.
        db_connection: Dict with at least a ``url`` key (SQLAlchemy connection URL).
        schedule:      Cron expression or ``None`` for manual-only.
        start_date:    DAG start date; defaults to 2024-01-01 UTC when ``None``.
        end_date:      Optional DAG end date.
        description:   Optional DAG description.

    Returns:
        A string containing valid Python source code for an Airflow DAG file.
    """
    # Warn if db_connection contains a raw URL with potential credentials
    if db_connection and "url" in db_connection:
        url = db_connection["url"]
        if "@" in str(url) and "://" in str(url):
            logger.warning(
                "db_connection contains a URL with possible inline credentials. "
                "Consider using conn_id (Airflow Connection) instead to avoid writing secrets to DAG files."
            )

    config_payload = {
        "sql": sql,
        "db_connection": db_connection or {},
    }
    config_json = json.dumps(config_payload, ensure_ascii=False, indent=4)

    effective_start = start_date or datetime(2024, 1, 1, tzinfo=timezone.utc)
    end_date_repr = (
        f"datetime({end_date.year}, {end_date.month}, {end_date.day}, tzinfo=timezone.utc)" if end_date else "None"
    )

    effective_schedule = schedule if schedule and str(schedule).strip().lower() != "none" else None

    return _DAG_TEMPLATE.format(
        job_name=job_name,
        built_at=datetime.now(tz=timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
        config_json=config_json,
        dag_id_repr=repr(dag_id),
        description_repr=repr(description or f"Datus job: {job_name}"),
        schedule_repr=repr(effective_schedule),
        start_year=effective_start.year,
        start_month=effective_start.month,
        start_day=effective_start.day,
        end_date_repr=end_date_repr,
    )
